### ISSUE TITLE
Inference works just once

### ISSUE THREAD

**Issue by vadi2** [lxe/simple-llama-finetuner#12] opened 2023-03-22 16:03 UTC
When I first load a model and ask it to infer, I get a good result. On a second inference it ignores what it should respond with and just keeps on generating more on the original input text. On the third inference, it just gives stacktraces and any subsequent inferences repeat the stacktraces:

```
Traceback (most recent call last):
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/gradio/helpers.py", line 587, in tracked_fn
    response = fn(*args)
  File "/home/vadi/Programs/simple-llama-finetuner/main.py", line 67, in generate_text
    model = PeftModel.from_pretrained(
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/peft/peft_model.py", line 138, in from_pretrained
    remove_hook_from_submodules(model)
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/accelerate/hooks.py", line 407, in remove_hook_from_submodules
    remove_hook_from_submodules(child)
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/accelerate/hooks.py", line 405, in remove_hook_from_submodules
    remove_hook_from_module(module)
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/accelerate/hooks.py", line 187, in remove_hook_from_module
    delattr(module, "_hf_hook")
  File "/home/vadi/Programs/miniconda3/envs/finetuner2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1328, in __delattr__
    super().__delattr__(name)
AttributeError: _hf_hook
```

Do others get the same?

**Comment by calz1** [comment] 2023-03-22 17:26
I get the same problem running it in Colab.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/gradio/helpers.py", line 587, in tracked_fn
    response = fn(*args)
  File "/content/simple-llama-finetuner/main.py", line 67, in generate_text
    model = PeftModel.from_pretrained(
  File "/usr/local/lib/python3.9/dist-packages/peft/peft_model.py", line 138, in from_pretrained
    remove_hook_from_submodules(model)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/hooks.py", line 405, in remove_hook_from_submodules
    remove_hook_from_module(module)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/hooks.py", line 187, in remove_hook_from_module
    delattr(module, "_hf_hook")
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1328, in __delattr__
    super().__delattr__(name)
AttributeError: _hf_hook`

**Comment by PopFlamingo** [comment] 2023-03-22 19:14
Hi! Same issue in Colab as well, running on the base GPU.

**Comment by lxe** [comment] 2023-03-22 20:57
I'm currently refactoring the model loading/unloading to fix the inference.

**Comment by lxe** [comment] 2023-03-22 22:49
Should be fixed in https://github.com/lxe/simple-llama-finetuner/commit/ecf29d859062f256b5b393e3ceeba8f25b69a263

**Comment by PopFlamingo** [comment] 2023-03-22 22:50
@lxe Awesome! Thanks a lot! Will try this and report here.

**Comment by PopFlamingo** [comment] 2023-03-22 23:11
Loading the model right after training still caused an error (unfortunately forgot to save the traceback before re-running the cell), but once I re-ran the cell I have been able to keep using the model without errors like it used to !

**Comment by lxe** [comment] 2023-03-22 23:38
> Loading the model right after training still caused an error (unfortunately forgot to save the traceback before re-running the cell), but once I re-ran the cell I have been able to keep using the model without errors like it used to !

Are you running on Colab or elsewhere?

**Comment by PopFlamingo** [comment] 2023-03-22 23:39
@lxe I'm running on Collab

**Comment by lxe** [comment] 2023-03-22 23:42
I just merged another change that does a GC after inference. Try running the notebook again.

**Comment by PopFlamingo** [comment] 2023-03-23 03:24
@lxe I tried it again and got an error: `AttributeError: 'NoneType' object has no attribute 'device'`

Here is the full traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/gradio/helpers.py", line 587, in tracked_fn
    response = fn(*args)
  File "/content/simple-llama-finetuner/main.py", line 104, in generate_text
    output = model.generate(  # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/peft/peft_model.py", line 581, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py", line 1462, in generate
    return self.sample(
  File "/usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py", line 2478, in sample
    outputs = self(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/llama/modeling_llama.py", line 765, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/llama/modeling_llama.py", line 614, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/llama/modeling_llama.py", line 309, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/llama/modeling_llama.py", line 209, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/peft/tuners/lora.py", line 522, in forward
    result = super().forward(x)
  File "/usr/local/lib/python3.9/dist-packages/bitsandbytes/nn/modules.py", line 242, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/usr/local/lib/python3.9/dist-packages/bitsandbytes/autograd/_functions.py", line 488, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/usr/local/lib/python3.9/dist-packages/bitsandbytes/autograd/_functions.py", line 317, in forward
    state.CxB, state.SB = F.transform(state.CB, to_order=formatB)
  File "/usr/local/lib/python3.9/dist-packages/bitsandbytes/functional.py", line 1698, in transform
    prev_device = pre_call(A.device)
AttributeError: 'NoneType' object has no attribute 'device'
```

**Comment by lxe** [comment] 2023-03-23 03:25
I'm gonna close this as a duplicate of #6. 

This happens when there's not enough RAM on the colab host.

**Closed** 2023-03-23 03:25 UTC
Labels: bug

**Comment by vadi2** [comment] 2023-03-23 06:47
I can confirm inference works multiple times now. FTR I'm running this on an RTX 4080 with 16GB vram and that hasn't changed, so thanks for fixing this one!
